#!/bin/bash
# Task 1: Directory creation, files creation, concatenate files
mkdir -p my_folder
cd my_folder
echo "This is the content of my_file.txt" > my_file.txt
echo "This is the content of another_file.txt" > another_file.txt
cat another_file.txt >> my_file.txt
echo "Updated content of my_file.txt:"
cat my_file.txt
# listing files
ls -l
# Task 2: 20 create .txt files, rename first 5 files to .yml
for i in {1..20}; do
    echo "Content of file$i" > "file$i.txt"
done
for i in {1..5}; do
    mv "file$i.txt" "file$i.yml"
done
# showing letest created top 5 files
ls -lt | head -n 6 | tail -n 5
