#!/bin/bash
# Task 1: Directory creation, files creation, concatenate files
mkdir -p my_folder
cd my_folder
echo "This is the content of my_file.txt" > my_file.txt
echo "This is the content of another_file.txt" > another_file.txt
cat another_file.txt >> my_file.txt
echo "Updated content of my_file.txt:"
cat my_file.txt
# listing files
ls -l
